import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



const inter = localFont({
  src: [
    {
      path: "./fonts/static/Inter_24pt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/static/Inter_24pt-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/static/Inter_24pt-ExtraBold.ttf",
      weight: "800",
      style: "extrabold",
    },
   
  ],
  variable: "--font-inter",
});


    
//     {
//       path: './fonts/WorkSans-Regular.ttf',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: './fonts/WorkSans-Bold.ttf',
//       weight: '700',
//       style: 'bold',
//     },
//     {
//       path: './fonts/WorkSans-Light.ttf',
//       weight: '300',
//       style: 'light',
//     },
//     {
//       path:'./fonts/WorkSans-ExtraBold.ttf',
//       weight: '800',
//       style: 'extrabold',  
//     },
//     {
//       path:'./fonts/WorkSans-SemiBold.ttf',
//       weight: '700',
//       style: 'semibold',  
//     },
//     {
//       path:'./fonts/WorkSans-ExtraLight.ttf',
//       weight: '200',
//       style: 'extralight',  
//     }
//   ],
//   variable: '--font-worksans',
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.5.0/remixicon.min.css" integrity="sha512-T7lIYojLrqj7eBrV1NvUSZplDBi8mFyIEGFGdox8Bic92Col3GVrscbJkL37AJoDmF2iAh81fRpO4XZukI6kbA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body
        className={`${geistSans.variable} ${inter.variable}   antialiased`}
      >
        <div className="bg-[#D2982D]">
          <Navbar/>
          {children}
          <Footer/>
          
        </div>
      </body>
    </html>
  );
}
